--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xpocketmc/LandProtections
build-by-default: true
branches:
  - master
projects:
  LandProtections:
    path: ""
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.4
      - src: AID-LEARNING/Commando/Commando
        version: ^3.1.0
...
